# Generated by Django 4.2.29 on 2026-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_address_employee_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/%Y/%m/'),
        ),
    ]
